### ISSUE TITLE
campaignion_foundation_form_alter() is broken

### ISSUE THREAD

**Issue by torotil** [moreonion/campaignion_foundation#4]
Problems with [campaignion_foundation_form_alter()](https://github.com/moreonion/campaignion_foundation/blob/16c8844bb3e3f4a8e3fc78b9f897c85879a792a2/template.php#L146):
- In general: Should this apply to *all* forms or only webforms? If the latter then it should be `campaignion_foundation_form_webform_client_form_alter()`.
- This function makes several assumptions about buttons being present that don’t hold for all forms.

**Comment by katzmo** [comment]
It applies/should apply to all forms with an 'actions' array (that are not just webforms). I don’t think it can (directly) cause any errors when we add items to a sub-array that didn’t exists before? But it might cause confusion/errors later when it seems like a button is present that actually isn’t? :thinking:

**Comment by torotil** [comment]
> But it might cause confusion/errors later when it seems like a button is present that actually isn’t?

I’d rather test that. I think I remember cases where this does cause problems … and yes it might confuse other code.
